### ISSUE TITLE
Guidance on versioning and bundled tools

### ISSUE THREAD

**Issue by alastairtree** [OctopusDeploy/WorkerTools#27]
Hello - thanks for this repo/image. It is very useful.

Do you have any guidance on how updates to tools are going to be managed and documented? For example I may have many deployment projects that depend on different versions of terraform - say 0.12, 13 14 and 15 . Ideally my steps could just depend on corresponding tags or versions of worker tools. But for that to work I need good docs on what is bundled with what version of worker tools, and a commitment to update/maintain new versions (and docs!) going forwards. It will also get unruly as there will be many combinations of the many bundled tools.

AppVeyor handle [this same problem ](https://www.appveyor.com/docs/linux-images-software/)by installing many versions of tools on the same image at a predictable path, and commit to maintaining key versions of each dependency long term (for example the last 3 minor versions plus the latest minor of the previous 3 major versions, plus any LTS releases). It means bigger images but far fewer flavours of image.

Some tools like AZ CLI only really need one version - the latest - as they tend to be very backwards compatible. But some tools like terraform are more like an SDK and require you to pick which version you use, and decide when you want to migrate to the new one.

Are there any plans/guidance on how we should adopt these tools? Or is this really a sample image, and we are expected to roll our own?

**Comment by alastairtree** [comment]
As an example - [this PR](https://github.com/OctopusDeploy/WorkerTools/pull/24) would break anyone who was using the latest tag of the worker tools image and building terraform as there are breaking changes for terraform config/state files between 13 and 14 version of terraform. If the image had the most recent terraform cli 0.13 installed at `/usr/lib/terraform0.13` and the latests 14 at `/usr/lib/terraform0.14` say, then you can just use the terraform custom path variable in your deployment to select the version you need without needing to change the image

**Comment by andrewabest** [comment]
Hello @alastairtree,

Thanks for the detailled post, I appreciate the effort you've put into providing examples of how some other tools in this ecosystem handle the challenge of curating the external tooling required to interact with third party services.

> Do you have any guidance on how updates to tools are going to be managed and documented?

We have some improvements we are going to make to these tools in the short term, I'll go through them below, and also provide some advice on how to use the tools.

Documentation
===

For **documentation**, we will update the ReadMe (both github and dockerhub) and link to the list of all of the current tools provided on each OS and which versions they are. The source of truth for these versions is the Dockerfile for each OS:

https://github.com/OctopusDeploy/WorkerTools/blob/master/ubuntu.18.04/Dockerfile#L3-L17

We call this out in [our documentation](https://octopus.com/docs/projects/steps/execution-containers-for-workers#worker-tools-images) but I agree it could be a lot more clear / transparent to assist people trying to make decisions.

We are also going to update the container build scripts to pin _all_ of the tool versions, to ensure the versions available in the built container are predictable and stable. A couple of the tools are pulling `vLatest` with each build, which isn't ideal.

This should get us to a point where it is easy to understand what tools are available in the latest build of each container image.

If you wanted to find an earlier version of a tool, you would need to look through [the releases](https://github.com/OctopusDeploy/WorkerTools/releases) to find the version you wanted.

Management
===

For **management**, we are updating the tools currently on a best-effort basis. Our intention is that the repository should contain the latest stable versions of all of the tools. Automating this process is on our radar, but not a current priority.

The images we publish are [semantically versioned](https://semver.org/). To ensure stability within your deployment processes, we recommend using the full `major.minor.patch` tag when using our worker tools container within your deployment processes (for example, use `:2.0.2-ubuntu.18.04`, not `ubuntu.18.04`).

If you wanted a tool that was not yet available, you can submit a PR like the one linked. We will ensure to tag it appropriately, following semver rules, so that if it is a breaking change, the version change will make this obvious. If you have ensured to use the full tag in your processes, these updates won't impact you.

BYO
===

If the tools or the way they are managed don't fit your particular use case, it isn't too hard to [create your own images](https://octopus.com/docs/projects/steps/execution-containers-for-workers#which-image) to use as execution containers. 

Future
===

On our radar for future consideration is finer-grained tool containers. The current tool container is a bit of a "kitchen sink" of devops tools - designed as a general purpose set of tools that will help people in all sorts of deployment scenarios. The tradeoff here is that the they are larger and more complex images. 

We may move to publishing a set of smaller, focussed containers. This would shrink image sizes, and also make it more clear that when an image was updated, it was likely to update the version of the specific tool it was providing.

I hope that sheds some light on things for you @alastairtree - please let me know if there is any other information that might be a help, or if you have any further feedback on the above!

**Comment by lukebailey** [comment]
Following up on the above response to see if there is any update on the creation of smaller images?

I raised a simialr feature request here: https://help.octopus.com/t/smaller-base-image-for-worker-tools-execution-containers/26908

The idea being that it would be great to have a small base image (ideally Alpine) that we can then specify the tools/version we need without additional noise (for example the Google CLI isn't something we would need)

**Comment by mcasperson** [comment]
Hi @lukebailey,

Improving the supplied images is still on our radar, but is not on our current backlog of work. We do however have documentation on how to create your own images in the chapter called "Verifiable deployments" from the ebook [The ten pillars of pragmatic Kubernetes deployments with Octopus](https://github.com/OctopusDeploy/TenPillarsK8s/releases/latest/download/tenpillarsk8s.pdf) which you can follow to create more streamlined images that target your own specific use case.

**Comment by lukebailey** [comment]
Thanks @mcasperson that is what we were looking for, could I suggest that the section you reference in the book is published on the main Octopus documentation site? This would be much easier to find for others.

For anyone else interesting this is the most basic (supported) Docker image that can run Calamari (PowerShell included as we commonly use this over bash to run our scripts). From this base image we then add other tooling like Terraform and Azure/AWS CLI

```
FROM ubuntu:20.04

ARG POWERSHELL_VERSION=7.1.3\*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        unzip \
        apt-transport-https \
        software-properties-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Powershell core
# https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#ubuntu-2004
RUN curl -LO -k "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb" && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    add-apt-repository universe && \
    apt-get install -y --no-install-recommends \
        powershell=${POWERSHELL_VERSION} && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -f packages-microsoft-prod.deb
```

**Comment by harrisonmeister** [comment]
> Thanks @mcasperson that is what we were looking for, could I suggest that the section you reference in the book is published on the main Octopus documentation site? This would be much easier to find for others.
> 
> For anyone else interesting this is the most basic (supported) Docker image that can run Calamari (PowerShell included as we commonly use this over bash to run our scripts). From this base image we then add other tooling like Terraform and Azure/AWS CLI
> 
> ```
> FROM ubuntu:20.04
> 
> ARG POWERSHELL_VERSION=7.1.3\*
> 
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends \
>         curl \
>         unzip \
>         apt-transport-https \
>         software-properties-common && \
>     apt-get clean && \
>     rm -rf /var/lib/apt/lists/*
> 
> # Powershell core
> # https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#ubuntu-2004
> RUN curl -LO -k "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb" && \
>     dpkg -i packages-microsoft-prod.deb && \
>     apt-get update && \
>     add-apt-repository universe && \
>     apt-get install -y --no-install-recommends \
>         powershell=${POWERSHELL_VERSION} && \
>     apt-get clean && \
>     rm -rf /var/lib/apt/lists/* && \
>     rm -f packages-microsoft-prod.deb
> ```

Hi @lukebailey - that's great feedback. I'll see what I can do to get this section updated - https://octopus.com/docs/projects/steps/execution-containers-for-workers#custom-docker-images

**Comment by harrisonmeister** [comment]
@lukebailey - the docs have been updated
